# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-03-08 08:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carbrand',
            name='usedcar',
        ),
        migrations.RemoveField(
            model_name='cartype',
            name='usedcar',
        ),
        migrations.AddField(
            model_name='usedcar',
            name='carbrand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sale.CarBrand'),
        ),
        migrations.AddField(
            model_name='usedcar',
            name='cardebt',
            field=models.BooleanField(default=False, verbose_name='是否有债务'),
        ),
        migrations.AddField(
            model_name='usedcar',
            name='carisbuy',
            field=models.BooleanField(default=False, verbose_name='是否购买'),
        ),
        migrations.AddField(
            model_name='usedcar',
            name='carpic',
            field=models.ImageField(default='', upload_to='img/car', verbose_name='图片'),
        ),
        migrations.AddField(
            model_name='usedcar',
            name='carprocedures',
            field=models.BooleanField(default=True, verbose_name='手续齐全'),
        ),
        migrations.AddField(
            model_name='usedcar',
            name='cartitle',
            field=models.CharField(max_length=50, null=True, verbose_name='车名'),
        ),
        migrations.AddField(
            model_name='usedcar',
            name='cartype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sale.CarType'),
        ),
        migrations.AlterField(
            model_name='usedcar',
            name='caraddress',
            field=models.CharField(max_length=100, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='usedcar',
            name='carcolor',
            field=models.CharField(max_length=30, null=True, verbose_name='颜色'),
        ),
        migrations.AlterField(
            model_name='usedcar',
            name='carengine',
            field=models.CharField(max_length=50, null=True, verbose_name='引擎'),
        ),
        migrations.AlterField(
            model_name='usedcar',
            name='carfixed',
            field=models.BooleanField(default=0, verbose_name='维修记录'),
        ),
        migrations.AlterField(
            model_name='usedcar',
            name='carhistory',
            field=models.TextField(verbose_name='车辆历史'),
        ),
        migrations.AlterField(
            model_name='usedcar',
            name='carid',
            field=models.CharField(max_length=30, verbose_name='订单编号'),
        ),
        migrations.AlterField(
            model_name='usedcar',
            name='carinfo',
            field=models.TextField(verbose_name='车况'),
        ),
        migrations.AlterField(
            model_name='usedcar',
            name='carisallowed',
            field=models.IntegerField(choices=[(0, '等待审核'), (1, '正在审核'), (2, '审核通过'), (3, '审核失败')], default=0, verbose_name='审核状态'),
        ),
        migrations.AlterField(
            model_name='usedcar',
            name='carisdel',
            field=models.BooleanField(default=0, verbose_name='是否删除订单'),
        ),
        migrations.AlterField(
            model_name='usedcar',
            name='carofnewprice',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='新车价格'),
        ),
        migrations.AlterField(
            model_name='usedcar',
            name='carprice',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='卖价'),
        ),
        migrations.AlterField(
            model_name='usedcar',
            name='carpubdate',
            field=models.DateTimeField(verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='usedcar',
            name='carpushnum',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2, verbose_name='排量'),
        ),
        migrations.AlterField(
            model_name='usedcar',
            name='carrun',
            field=models.FloatField(default=0, verbose_name='公里数'),
        ),
        migrations.AlterField(
            model_name='usedcar',
            name='carviews',
            field=models.IntegerField(verbose_name='浏览人数'),
        ),
        migrations.AlterField(
            model_name='usedcar',
            name='caryear',
            field=models.CharField(max_length=20, verbose_name='买入日期'),
        ),
    ]
