# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-03-08 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_auto_20190308_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usedcar',
            name='carid',
            field=models.CharField(max_length=30, verbose_name='编号'),
        ),
    ]
