"""empty message

Revision ID: febceb928a28
Revises: 
Create Date: 2019-01-28 15:11:07.450658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'febceb928a28'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wife',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wname', sa.String(length=30), nullable=False),
    sa.Column('wage', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wife')
    # ### end Alembic commands ###
