# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-03-08 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0002_auto_20190308_1513'),
    ]

    operations = [
        migrations.DeleteModel(
            name='carbrand',
        ),
        migrations.DeleteModel(
            name='usedcar',
        ),
        migrations.AlterModelOptions(
            name='usercard',
            options={'verbose_name': '用户银行卡表', 'verbose_name_plural': '用户银行卡表'},
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='uemail',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterModelTable(
            name='usercard',
            table='usercard',
        ),
    ]
