# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-03-08 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0004_auto_20190308_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercard',
            name='cardbank',
            field=models.IntegerField(choices=[(0, '中国银行'), (1, '工商银行')], default=0, verbose_name='开户行'),
        ),
        migrations.AddField(
            model_name='usercard',
            name='cardstatus',
            field=models.IntegerField(choices=[(0, '余额不足'), (1, '可以支付')], default=0, verbose_name='银行卡状态'),
        ),
        migrations.AddField(
            model_name='usercard',
            name='cardtype',
            field=models.IntegerField(choices=[(0, '储蓄卡'), (1, '信用卡')], default=0, verbose_name='银行卡类型'),
        ),
        migrations.AlterField(
            model_name='usercard',
            name='cardid',
            field=models.CharField(max_length=30, verbose_name='卡号'),
        ),
        migrations.AlterField(
            model_name='usercard',
            name='cardname',
            field=models.CharField(max_length=30, verbose_name='开户名'),
        ),
    ]
