"""empty message

Revision ID: f79cf96f571a
Revises: 
Create Date: 2019-01-28 15:34:54.074856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f79cf96f571a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('uemail', sa.String(length=30), nullable=False),
    sa.Column('uaddress', sa.String(length=30), nullable=True),
    sa.Column('upwd', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uaddress'),
    sa.UniqueConstraint('uemail'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
